#ifndef FITGEE_H
#define FITGEE_H

#include <RcppArmadillo.h>

arma::vec update_beta_gee_cc(const arma::vec& y_vector,
                             const arma::mat& model_matrix,
                             const arma::vec& id_vector,
                             const arma::vec& repeated_vector,
                             const arma::vec& weights_vector,
                             const char* link,
                             const char* family,
                             const arma::vec& beta_vector,
                             const arma::vec& mu_vector,
                             const arma::vec& eta_vector,
                             const char* correlation_structure,
                             const arma::vec& alpha_vector,
                             const double& phi);

arma::vec update_beta_naive_cc(const arma::vec& y_vector,
                               const arma::mat& model_matrix,
                               const arma::vec& id_vector,
                               const arma::vec& repeated_vector,
                               const arma::vec& weights_vector,
                               const char* link,
                               const char* family,
                               const arma::vec& beta_vector,
                               const arma::vec& mu_vector,
                               const arma::vec& eta_vector,
                               const char* correlation_structure,
                               const arma::vec& alpha_vector,
                               const double& phi);

arma::vec update_beta_robust_cc(const arma::vec& y_vector,
                                const arma::mat& model_matrix,
                                const arma::vec& id_vector,
                                const arma::vec& repeated_vector,
                                const arma::vec& weights_vector,
                                const char* link,
                                const char* family,
                                const arma::vec& beta_vector,
                                const arma::vec& mu_vector,
                                const arma::vec& eta_vector,
                                const char* correlation_structure,
                                const arma::vec& alpha_vector,
                                const double& phi);

arma::vec update_beta_empirical_cc(const arma::vec& y_vector,
                                   const arma::mat& model_matrix,
                                   const arma::vec& id_vector,
                                   const arma::vec& repeated_vector,
                                   const arma::vec& weights_vector,
                                   const char* link,
                                   const char* family,
                                   const arma::vec& beta_vector,
                                   const arma::vec& mu_vector,
                                   const arma::vec& eta_vector,
                                   const char* correlation_structure,
                                   const arma::vec& alpha_vector,
                                   const double& phi);

arma::vec update_beta_jeffreys_cc(const arma::vec& y_vector,
                                  const arma::mat& model_matrix,
                                  const arma::vec& id_vector,
                                  const arma::vec& repeated_vector,
                                  const arma::vec& weights_vector,
                                  const char* link,
                                  const char* family,
                                  const arma::vec& beta_vector,
                                  const arma::vec& mu_vector,
                                  const arma::vec& eta_vector,
                                  const char* correlation_structure,
                                  const arma::vec& alpha_vector,
                                  const double& phi,
                                  const double& jeffreys_power);

arma::vec update_beta_cc(const arma::vec& y_vector,
                         const arma::mat& model_matrix,
                         const arma::vec& id_vector,
                         const arma::vec& repeated_vector,
                         const arma::vec& weights_vector,
                         const char* link,
                         const char* family,
                         const arma::vec& beta_vector,
                         const arma::vec& mu_vector,
                         const arma::vec& eta_vector,
                         const char* correlation_structure,
                         const arma::vec& alpha_vector,
                         const double& phi,
                         const double& jeffreys_power,
                         const char* method);

Rcpp::List fit_geesolver_cc(const arma::vec& y_vector,
                            const arma::mat& model_matrix,
                            const arma::vec& id_vector,
                            const arma::vec& repeated_vector,
                            const arma::vec& weights_vector,
                            const char* link,
                            const char* family,
                            arma::vec beta_vector,
                            const arma::vec& offset,
                            const int& maxiter,
                            const double& tolerance,
                            const int& step_maxiter,
                            const int& step_multiplier,
                            const double& jeffreys_power,
                            const char* method,
                            int use_params,
                            arma::vec alpha_vector,
                            const int& alpha_fixed,
                            const char* correlation_structure,
                            const int& mdependence,
                            double phi,
                            const int& phi_fixed);

#endif // FITGEE_H
