# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ar1_cormatrix_formulated <- function(param_no, rho_hat) {
    .Call(`_matrixgee_ar1_cormatrix_formulated`, param_no, rho_hat)
}

correlation_cols_calc_cpp <- function(residuals, sample_size, rows_no, cols_no, parameters_no, corstr_cols, dispersion_parameter) {
    .Call(`_matrixgee_correlation_cols_calc_cpp`, residuals, sample_size, rows_no, cols_no, parameters_no, corstr_cols, dispersion_parameter)
}

correlation_cols_updated_cpp <- function(residuals, sample_size, rows_no, cols_no, parameters_no, corstr_cols, dispersion_parameter) {
    .Call(`_matrixgee_correlation_cols_updated_cpp`, residuals, sample_size, rows_no, cols_no, parameters_no, corstr_cols, dispersion_parameter)
}

correlation_general <- function(residuals, sample_size, rows_no, cols_no, parameters_no, corstr, dispersion_parameter) {
    .Call(`_matrixgee_correlation_general`, residuals, sample_size, rows_no, cols_no, parameters_no, corstr, dispersion_parameter)
}

correlation_general_updated <- function(residuals, sample_size, rows_no, cols_no, parameters_no, corstr, dispersion_parameter) {
    .Call(`_matrixgee_correlation_general_updated`, residuals, sample_size, rows_no, cols_no, parameters_no, corstr, dispersion_parameter)
}

correlation_rows_updated_cpp <- function(residuals, sample_size, rows_no, cols_no, parameters_no, corstr_rows, dispersion) {
    .Call(`_matrixgee_correlation_rows_updated_cpp`, residuals, sample_size, rows_no, cols_no, parameters_no, corstr_rows, dispersion)
}

get_covariance_matrices_cc <- function(y_vector, model_matrix, id_vector, repeated_vector, weights_vector, link, family, mu_vector, eta_vector, correlation_structure, alpha_vector, phi) {
    .Call(`_matrixgee_get_covariance_matrices_cc`, y_vector, model_matrix, id_vector, repeated_vector, weights_vector, link, family, mu_vector, eta_vector, correlation_structure, alpha_vector, phi)
}

covariates_upd <- function(covariates, sample_size, rows_no, cols_no) {
    .Call(`_matrixgee_covariates_upd`, covariates, sample_size, rows_no, cols_no)
}

update_beta_gee_cc <- function(y_vector, model_matrix, id_vector, repeated_vector, weights_vector, link, family, beta_vector, mu_vector, eta_vector, correlation_structure, alpha_vector, phi) {
    .Call(`_matrixgee_update_beta_gee_cc`, y_vector, model_matrix, id_vector, repeated_vector, weights_vector, link, family, beta_vector, mu_vector, eta_vector, correlation_structure, alpha_vector, phi)
}

update_beta_naive_cc <- function(y_vector, model_matrix, id_vector, repeated_vector, weights_vector, link, family, beta_vector, mu_vector, eta_vector, correlation_structure, alpha_vector, phi) {
    .Call(`_matrixgee_update_beta_naive_cc`, y_vector, model_matrix, id_vector, repeated_vector, weights_vector, link, family, beta_vector, mu_vector, eta_vector, correlation_structure, alpha_vector, phi)
}

update_beta_robust_cc <- function(y_vector, model_matrix, id_vector, repeated_vector, weights_vector, link, family, beta_vector, mu_vector, eta_vector, correlation_structure, alpha_vector, phi) {
    .Call(`_matrixgee_update_beta_robust_cc`, y_vector, model_matrix, id_vector, repeated_vector, weights_vector, link, family, beta_vector, mu_vector, eta_vector, correlation_structure, alpha_vector, phi)
}

update_beta_empirical_cc <- function(y_vector, model_matrix, id_vector, repeated_vector, weights_vector, link, family, beta_vector, mu_vector, eta_vector, correlation_structure, alpha_vector, phi) {
    .Call(`_matrixgee_update_beta_empirical_cc`, y_vector, model_matrix, id_vector, repeated_vector, weights_vector, link, family, beta_vector, mu_vector, eta_vector, correlation_structure, alpha_vector, phi)
}

update_beta_jeffreys_cc <- function(y_vector, model_matrix, id_vector, repeated_vector, weights_vector, link, family, beta_vector, mu_vector, eta_vector, correlation_structure, alpha_vector, phi, jeffreys_power) {
    .Call(`_matrixgee_update_beta_jeffreys_cc`, y_vector, model_matrix, id_vector, repeated_vector, weights_vector, link, family, beta_vector, mu_vector, eta_vector, correlation_structure, alpha_vector, phi, jeffreys_power)
}

update_beta_cc <- function(y_vector, model_matrix, id_vector, repeated_vector, weights_vector, link, family, beta_vector, mu_vector, eta_vector, correlation_structure, alpha_vector, phi, jeffreys_power, method) {
    .Call(`_matrixgee_update_beta_cc`, y_vector, model_matrix, id_vector, repeated_vector, weights_vector, link, family, beta_vector, mu_vector, eta_vector, correlation_structure, alpha_vector, phi, jeffreys_power, method)
}

fit_geesolver_cc <- function(y_vector, model_matrix, id_vector, repeated_vector, weights_vector, link, family, beta_vector, offset, maxiter, tolerance, step_maxiter, step_multiplier, jeffreys_power, method, use_params, alpha_vector, alpha_fixed, correlation_structure, mdependence, phi, phi_fixed) {
    .Call(`_matrixgee_fit_geesolver_cc`, y_vector, model_matrix, id_vector, repeated_vector, weights_vector, link, family, beta_vector, offset, maxiter, tolerance, step_maxiter, step_multiplier, jeffreys_power, method, use_params, alpha_vector, alpha_fixed, correlation_structure, mdependence, phi, phi_fixed)
}

get_naive_matrix_inverse_independence <- function(y_vector, model_matrix, id_vector, link, family, mu_vector, eta_vector, phi) {
    .Call(`_matrixgee_get_naive_matrix_inverse_independence`, y_vector, model_matrix, id_vector, link, family, mu_vector, eta_vector, phi)
}

get_gee_criteria_sc_cw <- function(y_vector, id_vector, repeated_vector, family, mu_vector, correlation_structure, alpha_vector, phi, weights_vector) {
    .Call(`_matrixgee_get_gee_criteria_sc_cw`, y_vector, id_vector, repeated_vector, family, mu_vector, correlation_structure, alpha_vector, phi, weights_vector)
}

matrix_to_long_dataframe_cpp <- function(data, sample_size, rows_no, cols_no) {
    .Call(`_matrixgee_matrix_to_long_dataframe_cpp`, data, sample_size, rows_no, cols_no)
}

vector_to_long_dataframe_cpp <- function(data, sample_size, rows_no, cols_no) {
    .Call(`_matrixgee_vector_to_long_dataframe_cpp`, data, sample_size, rows_no, cols_no)
}

arma2vec <- function(x) {
    .Call(`_matrixgee_arma2vec`, x)
}

vec2arma <- function(x) {
    .Call(`_matrixgee_vec2arma`, x)
}

linkfun_rcpp <- function(link, mu_vector) {
    .Call(`_matrixgee_linkfun_rcpp`, link, mu_vector)
}

linkfun <- function(link, mu_vector) {
    .Call(`_matrixgee_linkfun`, link, mu_vector)
}

linkinv_rcpp <- function(link, eta_vector) {
    .Call(`_matrixgee_linkinv_rcpp`, link, eta_vector)
}

linkinv <- function(link, eta_vector) {
    .Call(`_matrixgee_linkinv`, link, eta_vector)
}

mueta_rcpp <- function(link, eta_vector) {
    .Call(`_matrixgee_mueta_rcpp`, link, eta_vector)
}

mueta <- function(link, eta_vector) {
    .Call(`_matrixgee_mueta`, link, eta_vector)
}

mueta2_rcpp <- function(link, eta_vector) {
    .Call(`_matrixgee_mueta2_rcpp`, link, eta_vector)
}

mueta2 <- function(link, eta_vector) {
    .Call(`_matrixgee_mueta2`, link, eta_vector)
}

mueta3_rcpp <- function(link, eta_vector) {
    .Call(`_matrixgee_mueta3_rcpp`, link, eta_vector)
}

mueta3 <- function(link, eta_vector) {
    .Call(`_matrixgee_mueta3`, link, eta_vector)
}

valideta <- function(link, eta_vector) {
    .Call(`_matrixgee_valideta`, link, eta_vector)
}

validmu <- function(family, mu_vector) {
    .Call(`_matrixgee_validmu`, family, mu_vector)
}

matrixgee_cpp <- function(data, covariates, intercept, sample_size, rows_no, cols_no, max_iter, tol, corstr_rows, corstr_cols) {
    .Call(`_matrixgee_matrixgee_cpp`, data, covariates, intercept, sample_size, rows_no, cols_no, max_iter, tol, corstr_rows, corstr_cols)
}

matrixgee_cpp_nokron <- function(data, covariates, intercept, sample_size, rows_no, cols_no, max_iter, tol, corstr) {
    .Call(`_matrixgee_matrixgee_cpp_nokron`, data, covariates, intercept, sample_size, rows_no, cols_no, max_iter, tol, corstr)
}

get_pearson_residuals <- function(family, y_vector, mu_vector, weights_vector) {
    .Call(`_matrixgee_get_pearson_residuals`, family, y_vector, mu_vector, weights_vector)
}

get_phi_hat <- function(pearson_residuals_vector, params_no) {
    .Call(`_matrixgee_get_phi_hat`, pearson_residuals_vector, params_no)
}

alpha_hat_exchangeable <- function(pearson_residuals_vector, id_vector, phi, params_no) {
    .Call(`_matrixgee_alpha_hat_exchangeable`, pearson_residuals_vector, id_vector, phi, params_no)
}

alpha_hat_ar1 <- function(pearson_residuals_vector, id_vector, repeated_vector, phi, params_no) {
    .Call(`_matrixgee_alpha_hat_ar1`, pearson_residuals_vector, id_vector, repeated_vector, phi, params_no)
}

alpha_hat_unstructured <- function(pearson_residuals_vector, id_vector, repeated_vector, phi, params_no) {
    .Call(`_matrixgee_alpha_hat_unstructured`, pearson_residuals_vector, id_vector, repeated_vector, phi, params_no)
}

alpha_hat_mdependent <- function(pearson_residuals_vector, id_vector, repeated_vector, phi, params_no, mdependence) {
    .Call(`_matrixgee_alpha_hat_mdependent`, pearson_residuals_vector, id_vector, repeated_vector, phi, params_no, mdependence)
}

alpha_hat_toeplitz <- function(pearson_residuals_vector, id_vector, repeated_vector, phi, params_no) {
    .Call(`_matrixgee_alpha_hat_toeplitz`, pearson_residuals_vector, id_vector, repeated_vector, phi, params_no)
}

get_alpha_hat <- function(correlation_structure, pearson_residuals_vector, id_vector, repeated_vector, phi, params_no, mdependence) {
    .Call(`_matrixgee_get_alpha_hat`, correlation_structure, pearson_residuals_vector, id_vector, repeated_vector, phi, params_no, mdependence)
}

correlation_independence <- function(dimension) {
    .Call(`_matrixgee_correlation_independence`, dimension)
}

correlation_exchangeable <- function(alpha_vector, dimension) {
    .Call(`_matrixgee_correlation_exchangeable`, alpha_vector, dimension)
}

correlation_ar1 <- function(alpha_vector, dimension) {
    .Call(`_matrixgee_correlation_ar1`, alpha_vector, dimension)
}

correlation_mdependent <- function(alpha_vector, dimension) {
    .Call(`_matrixgee_correlation_mdependent`, alpha_vector, dimension)
}

correlation_toeplitz <- function(alpha_vector) {
    .Call(`_matrixgee_correlation_toeplitz`, alpha_vector)
}

correlation_unstructured <- function(alpha_vector, dimension) {
    .Call(`_matrixgee_correlation_unstructured`, alpha_vector, dimension)
}

get_correlation_matrix <- function(correlation_structure, alpha_vector, dimension) {
    .Call(`_matrixgee_get_correlation_matrix`, correlation_structure, alpha_vector, dimension)
}

get_v_matrix_cc <- function(family, mu_vector, repeated_vector, phi, cor_matrix, weights_vector) {
    .Call(`_matrixgee_get_v_matrix_cc`, family, mu_vector, repeated_vector, phi, cor_matrix, weights_vector)
}

residuals_dispersion_helper <- function(model_residuals, sample_size, rows_no, cols_no, parameters_no) {
    .Call(`_matrixgee_residuals_dispersion_helper`, model_residuals, sample_size, rows_no, cols_no, parameters_no)
}

correlation_rows_calc_cpp <- function(residuals, sample_size, rows_no, cols_no, parameters_no, corstr_rows, dispersion_parameter) {
    .Call(`_matrixgee_correlation_rows_calc_cpp`, residuals, sample_size, rows_no, cols_no, parameters_no, corstr_rows, dispersion_parameter)
}

estimating_equations_gee_cc <- function(y_vector, model_matrix, id_vector, repeated_vector, weights_vector, link, family, beta_vector, mu_vector, eta_vector, correlation_structure, alpha_vector, phi) {
    .Call(`_matrixgee_estimating_equations_gee_cc`, y_vector, model_matrix, id_vector, repeated_vector, weights_vector, link, family, beta_vector, mu_vector, eta_vector, correlation_structure, alpha_vector, phi)
}

extract_upper_from_matrix <- function(kronecker_matrix) {
    .Call(`_matrixgee_extract_upper_from_matrix`, kronecker_matrix)
}

subset_matrix <- function(x, y) {
    .Call(`_matrixgee_subset_matrix`, x, y)
}

kappa_matrix <- function(dimension) {
    .Call(`_matrixgee_kappa_matrix`, dimension)
}

kronecker_left_identity_kappa <- function(x) {
    .Call(`_matrixgee_kronecker_left_identity_kappa`, x)
}

kronecker_identity_right_kappa <- function(x) {
    .Call(`_matrixgee_kronecker_identity_right_kappa`, x)
}

kappa_right <- function(x) {
    .Call(`_matrixgee_kappa_right`, x)
}

kronecker_sum_same <- function(x) {
    .Call(`_matrixgee_kronecker_sum_same`, x)
}

kronecker_vector_identity <- function(x) {
    .Call(`_matrixgee_kronecker_vector_identity`, x)
}

kronecker_vector_matrix <- function(x, y) {
    .Call(`_matrixgee_kronecker_vector_matrix`, x, y)
}

variance <- function(family, mu_vector) {
    .Call(`_matrixgee_variance`, family, mu_vector)
}

variancemu <- function(family, mu_vector) {
    .Call(`_matrixgee_variancemu`, family, mu_vector)
}

variancemu2 <- function(family, mu_vector) {
    .Call(`_matrixgee_variancemu2`, family, mu_vector)
}

